const fs = require('fs');
const paths = [
  'public/admin/login.html',
  'public/admin/index.html',
  'public/admin/js/admin.js',
  'public/js/app.js'
];
const replacements = [
  ['lang="zh-CN"', 'lang="vi"'],
  ['管理员登录 - GPT2API Node', 'Đăng nhập quản trị - GPT2API Node'],
  ['管理员登录', 'Đăng nhập quản trị'],
  ['GPT2API Node 管理系统', 'Hệ thống quản trị GPT2API Node'],
  ['用户名', 'Tên đăng nhập'],
  ['请输入用户名', 'Vui lòng nhập tên đăng nhập'],
  ['密码', 'Mật khẩu'],
  ['请输入密码', 'Vui lòng nhập mật khẩu'],
  ['登录', 'Đăng nhập'],
  ['默认账户:', 'Tài khoản mặc định:'],
  ['首次登录后请立即修改密码', 'Vui lòng thay đổi mật khẩu ngay sau lần đăng nhập đầu tiên'],
  ['登录中...', 'Đang đăng nhập...'],
  ['加载中...', 'Đang tải...'],
  ['文件读取失败:', 'Đọc tệp thất bại:'],
  ['管理后台 - GPT2API Node', 'Bảng điều khiển quản trị - GPT2API Node'],
  ['管理控制台', 'Bảng điều khiển quản trị'],
  ['GitHub 项目', 'Dự án GitHub'],
  ['仪表盘', 'Bảng điều khiển'],
  ['账号管理', 'Quản lý tài khoản'],
  ['数据分析', 'Phân tích dữ liệu'],
  ['系统设置', 'Cài đặt hệ thống'],
  ['管理员', 'Quản trị viên'],
  ['退出登录', 'Đăng xuất'],
  ['系统概览和实时数据', 'Tổng quan hệ thống và dữ liệu thời gian thực'],
  ['活跃密钥数量', 'Số khóa hoạt động'],
  ['账户令牌数量', 'Số token tài khoản'],
  ['今日请求', 'Yêu cầu hôm nay'],
  ['API 调用次数', 'Số lần gọi API'],
  ['成功率', 'Tỷ lệ thành công'],
  ['请求成功比例', 'Tỷ lệ yêu cầu thành công'],
  ['最近活动', 'Hoạt động gần đây'],
  ['暂无活动记录', 'Chưa có hoạt động'],
  ['API Keys 管理', 'Quản lý API Keys'],
  ['创建 API Key', 'Tạo API Key'],
  ['名称', 'Tên'],
  ['使用次数', 'Số lần sử dụng'],
  ['最后使用', 'Lần cuối sử dụng'],
  ['状态', 'Trạng thái'],
  ['操作', 'Thao tác'],
  ['账号管理 (Tokens)', 'Quản lý tài khoản (Tokens)'],
  ['账号总数:', 'Tổng tài khoản:'],
  ['负载均衡:', 'Cân bằng tải:'],
  ['轮询', 'Luân phiên'],
  ['随机', 'Ngẫu nhiên'],
  ['最少使用', 'Ít sử dụng nhất'],
  ['删除选中', 'Xóa mục đã chọn'],
  ['刷新全部额度', 'Làm mới toàn bộ hạn mức'],
  ['导入 JSON', 'Nhập JSON'],
  ['手动添加', 'Thêm thủ công'],
  ['额度', 'Hạn mức'],
  ['总请求', 'Tổng yêu cầu'],
  ['成功', 'Thành công'],
  ['失败', 'Thất bại'],
  ['过期时间', 'Thời gian hết hạn'],
  ['分页', 'Phân trang'],
  ['时间范围选择', 'Chọn khoảng thời gian'],
  ['时间范围：', 'Khoảng thời gian:'],
  ['24小时', '24 giờ'],
  ['7天', '7 ngày'],
  ['30天', '30 ngày'],
  ['统计卡片', 'Thẻ thống kê'],
  ['总请求数', 'Tổng yêu cầu'],
  ['成功请求', 'Yêu cầu thành công'],
  ['失败请求', 'Yêu cầu thất bại'],
  ['平均响应时间', 'Thời gian phản hồi trung bình'],
  ['请求量趋势', 'Xu hướng lượng yêu cầu'],
  ['模型使用分布', 'Phân phối sử dụng mô hình'],
  ['账号详细统计', 'Thống kê chi tiết tài khoản'],
  ['账号名称', 'Tên tài khoản'],
  ['最近请求日志', 'Nhật ký yêu cầu gần đây'],
  ['时间', 'Thời gian'],
  ['模型', 'Mô hình'],
  ['响应时间', 'Thời gian phản hồi'],
  ['修改密码', 'Thay đổi mật khẩu'],
  ['更多设置功能开发中...', 'Các chức năng cài đặt khác đang phát triển...'],
  ['名称（可选）', 'Tên (tùy chọn)'],
  ['例如：生产环境', 'Ví dụ: môi trường sản xuất'],
  ['取消', 'Hủy bỏ'],
  ['创建', 'Tạo'],
  ['手动添加 Token', 'Thêm Token thủ công'],
  ['Access Token', 'Access Token'],
  ['Refresh Token', 'Refresh Token'],
  ['粘贴 access_token', 'Dán access_token'],
  ['粘贴 refresh_token', 'Dán refresh_token'],
  ['导入 Token (JSON 文件)', 'Nhập Token (tệp JSON)'],
  ['支持的 JSON 格式：', 'Định dạng JSON hỗ trợ:'],
  ['账户名称', 'Tên tài khoản'],
  ['选择 JSON 文件', 'Chọn tệp JSON'],
  ['支持选择多个文件批量导入，或者直接粘贴 JSON 内容到下方文本框', 'Hỗ trợ chọn nhiều tệp để nhập hàng loạt, hoặc dán trực tiếp nội dung JSON vào ô bên dưới'],
  ['JSON 内容', 'Nội dung JSON'],
  ['粘贴 JSON 内容...', 'Dán nội dung JSON...'],
  ['预览（将导入 <span id="importCount">0</span> 个账户）', 'Xem trước (sẽ nhập <span id="importCount">0</span> tài khoản)'],
  ['预览', 'Xem trước'],
  ['开始导入', 'Bắt đầu nhập'],
  ['当前密码', 'Mật khẩu hiện tại'],
  ['新密码', 'Mật khẩu mới'],
  ['确认新密码', 'Xác nhận mật khẩu mới'],
  ['密码长度至少 6 位', 'Mật khẩu ít nhất 6 ký tự'],
  ['确认修改', 'Xác nhận thay đổi'],
  ['// 全局变量', '// Biến toàn cục'],
  ['// 页面加载时初始化', '// Khởi tạo khi trang tải xong'],
  ['// 检查认证状态', '// Kiểm tra trạng thái xác thực'],
  ['// 加载统计数据', '// Tải dữ liệu thống kê'],
  ['// 加载最近活动记录', '// Tải hoạt động gần đây'],
  ['// 计算时间差', '// Tính khoảng thời gian'],
  ['// 切换页面', '// Chuyển trang'],
  ['// 更新导航样式', '// Cập nhật kiểu điều hướng'],
  ['// 隐藏所有页面', '// Ẩn tất cả trang'],
  ['// 更新页面标题', '// Cập nhật tiêu đề trang'],
  ['// 切换账号管理标签', '// Chuyển tab quản lý tài khoản'],
  ['// 已移除，不再需要', '// Đã loại bỏ, không cần nữa'],
  ['// ==================== API Keys 管理 ====================', '// ==================== Quản lý API Keys ===================='],
  ['// ==================== Tokens 管理 ====================', '// ==================== Quản lý Tokens ===================='],
  ['// ==================== 批量删除功能 ====================', '// ==================== Chức năng xóa hàng loạt ===================='],
  ['// ==================== 日志管理 ====================', '// ==================== Quản lý nhật ký ===================='],
  ['// ==================== 负载均衡策略管理 ====================', '// ==================== Quản lý chiến lược cân bằng tải ===================='],
  ['// ==================== 修改密码 ====================', '// ==================== Thay đổi mật khẩu ===================='],
  ['// ==================== 工具函数 ====================', '// ==================== Hàm tiện ích ===================='],
  ['运行中', 'Đang chạy'],
  ['未知', 'Không xác định'],
  ['离线', 'Ngoại tuyến'],
  ['加载状态失败:', 'Tải trạng thái thất bại:'],
  ['加载模型失败:', 'Tải mô hình thất bại:'],
  ['思考中...', 'Đang suy nghĩ...'],
  ['开始对话吧！', 'Bắt đầu trò chuyện!'],
  ['设置功能开发中...', 'Chức năng cài đặt đang phát triển...'],
  ['状态已刷新！', 'Đã làm mới trạng thái!'],
  ['可用模型:', 'Mô hình khả dụng:'],
  ['获取模型列表失败:', 'Lấy danh sách mô hình thất bại:'],
  ['认证检查失败:', 'Kiểm tra xác thực thất bại:'],
  ['加载最近活动失败:', 'Tải hoạt động gần đây thất bại:'],
  ['刚刚', 'Vừa xong'],
  ['分钟前', ' phút trước'],
  ['小时前', ' giờ trước'],
  ['天前', ' ngày trước'],
  ['API Key 创建成功！\n\n', 'API Key tạo thành công!\n\n'],
  ['请妥善保存，此 Key 不会再次显示！', 'Vui lòng lưu kỹ, Key này sẽ không hiển thị lại!'],
  ['创建失败:', 'Tạo thất bại:'],
  ['操作失败:', 'Thao tác thất bại:'],
  ['确定要删除此 API Key 吗？', 'Bạn có chắc muốn xóa API Key này không?'],
  ['暂无 API Key', 'Chưa có API Key'],
  ['暂无 Token', 'Chưa có Token'],
  ['开始读取 ', 'Bắt đầu đọc '],
  ['读取文件 ', 'Đọc tệp '],
  ['文件 ', 'Tệp '],
  ['包含 ', ' chứa '],
  ['个 token', ' token'],
  ['文件解析失败:', 'Phân tích tệp thất bại:'],
  ['请先选择文件或粘贴 JSON 内容', 'Vui lòng chọn tệp hoặc dán nội dung JSON trước'],
  ['JSON 格式错误：未找到有效的 token 数据\n\n每个 token 必须包含 access_token 和 refresh_token 字段', 'Định dạng JSON sai: không tìm thấy dữ liệu token hợp lệ\n\nMỗi token phải chứa trường access_token và refresh_token'],
  ['JSON 解析失败：', 'Phân tích JSON thất bại:'],
  ['请先预览导入数据', 'Vui lòng xem trước dữ liệu nhập trước'],
  ['确定要导入 ', 'Bạn có chắc muốn nhập '],
  [' 个账户吗？', ' tài khoản không?'],
  ['导入成功！\n成功：', 'Nhập thành công!\nThành công: '],
  [' 个\n失败：', ' tài khoản\nThất bại: '],
  ['导入失败:', 'Nhập thất bại:'],
  ['Token 添加成功！', 'Thêm Token thành công!'],
  ['添加失败:', 'Thêm thất bại:'],
  ['确定要删除此 Token 吗？', 'Bạn có chắc muốn xóa Token này không?'],
  ['额度已更新\n总额度: ', 'Hạn mức đã được cập nhật\nTổng hạn mức: '],
  ['\n已使用: ', '\nĐã sử dụng: '],
  ['\n剩余: ', '\nCòn lại: '],
  ['刷新额度失败:', 'Làm mới hạn mức thất bại:'],
  ['确定要刷新所有账号的额度吗？这可能需要一些时间。', 'Bạn có chắc muốn làm mới hạn mức tất cả tài khoản không? Việc này có thể mất một thời gian.'],
  ['批量刷新完成\n成功:', 'Làm mới hàng loạt hoàn tất\nThành công:'],
  ['批量刷新失败:', 'Làm mới hàng loạt thất bại:'],
  ['请先选择要删除的账号', 'Vui lòng chọn tài khoản để xóa trước'],
  ['确定要删除选中的 ', 'Bạn có chắc muốn xóa '],
  [' 个账号吗？此操作不可恢复！', ' tài khoản đã chọn không? Hành động này không thể phục hồi!'],
  ['批量删除完成\n成功:', 'Xóa hàng loạt hoàn tất\nThành công:'],
  ['批量删除失败:', 'Xóa hàng loạt thất bại:'],
  ['加载图表失败:', 'Tải biểu đồ thất bại:'],
  ['暂无数据', 'Chưa có dữ liệu'],
  ['暂无日志', 'Chưa có nhật ký'],
  ['确定要退出登录吗？', 'Bạn có chắc muốn đăng xuất không?'],
  ['已复制到剪贴板！', 'Đã sao chép vào khay nhớ tạm!'],
  ['复制失败，请手动复制', 'Sao chép thất bại, vui lòng sao chép thủ công'],
  ['加载负载均衡策略失败:', 'Tải chiến lược cân bằng tải thất bại:'],
  ['负载均衡策略已更新为：', 'Chiến lược cân bằng tải đã cập nhật thành: '],
  ['两次输入的新密码不一致', 'Mật khẩu mới nhập lại không khớp'],
  ['密码长度至少 6 位', 'Mật khẩu phải có ít nhất 6 ký tự'],
  ['密码修改成功，请重新登录', 'Đổi mật khẩu thành công, vui lòng đăng nhập lại'],
  ['修改失败:', 'Thay đổi thất bại:']
];

for (const filepath of paths) {
  let content = fs.readFileSync(filepath, 'utf8');
  let changed = false;
  for (const [oldText, newText] of replacements) {
    if (content.includes(oldText)) {
      content = content.split(oldText).join(newText);
      changed = true;
    }
  }
  if (changed) {
    fs.writeFileSync(filepath, content, 'utf8');
    console.log('Updated', filepath);
  } else {
    console.log('No change', filepath);
  }
}

const re = /[\u4e00-\u9fff]+/g;
for (const filepath of paths) {
  const content = fs.readFileSync(filepath, 'utf8');
  const matches = new Set((content.match(re) || []));
  if (matches.size > 0) {
    console.log('Remaining Chinese in', filepath, ':');
    console.log([...matches].sort().join('; '));
  }
}
